// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef PIDGoalRotate_H
#define PIDGoalRotate_H


#include "Commands/Subsystem.h"
#include "../../Robot.h"
#include "../../RobotMap.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class PIDGoalRotate: public Command {
private:
	double tolerance =4*M_PI/180;
	double kP = 0.4;
	double kI = 0;
	double kD = 0;
	double errorLast;
	double errorDifference;
	double errorSum;
	double speed;
public:
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
	PIDGoalRotate();
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

	virtual void Initialize();
	virtual void Execute();
	virtual bool IsFinished();
	virtual void End();
	virtual void Interrupted();

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLES

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLES


};

#endif
