// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef PIDShoot_H
#define PIDShoot_H


#include "Commands/Subsystem.h"
#include "../../Robot.h"
#include "../../RobotMap.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class PIDShoot: public Command {
public:
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
	PIDShoot();
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

	virtual void Initialize();
	virtual void Execute();
	virtual bool IsFinished();
	virtual void End();
	virtual void Interrupted();

private:
	double const speedGoal = 1.0;
	double errorLast;
	double errorDifference;
	double errorSum;
	double speed;
	double kP = 1.0;
	double kI = 0.0;
	double kD = 0.12;

};

#endif
