// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef CHASSIS_H
#define CHASSIS_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
#include "CANTalon.h"
#include <cmath>

/**
 *
 *
 * @author ExampleAuthor
 */
class Chassis: public Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	std::shared_ptr<CANTalon> frontLeft;
	std::shared_ptr<CANTalon> frontRight;
	std::shared_ptr<CANTalon> backLeft;
	std::shared_ptr<CANTalon> backRight;
	std::shared_ptr<RobotDrive> robotDrive;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	bool flippedDirection;



public:
	Chassis();
	void InitDefaultCommand();
	void Drive();
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
	void FixJoystick();
	double GetBLSpeed();
	double GetBRSpeed();
	double GetFLSpeed();
	double GetFRSpeed();
	void SetBLSpeed(double speed);
	void SetBRSpeed(double speed);
	void SetFLSpeed(double speed);
	void SetFRSpeed(double speed);
	double GetBLVolt();
	double GetBRVolt();
	double GetFLVolt();
	double GetFRVolt();

	void CartesianDrive(double x, double y, double rotation, bool squaredinputs = true);
	void FlipDirection();
	bool IsFlipped();
};

#endif
