// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "Climber.h"
#include "../RobotMap.h"
#include "../Commands/Climb.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

Climber::Climber() :
		Subsystem("Climber") {
	Motor1 = RobotMap::climberMotor1;
	Motor2 = RobotMap::climberMotor2;
}

void Climber::InitDefaultCommand() {
	SetDefaultCommand(new Climb());
}

void Climber::setSpeed(double speed) {
	Motor1->Set(speed);
	Motor2->Set(speed);

}



// Put methods for controlling this subsystem
// here. Call these from Commands.

