// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "ShooterRamp.h"
#include "../RobotMap.h"
#include "../Commands/Shooting/ShootRamp.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

ShooterRamp::ShooterRamp() :
		Subsystem("ShooterRamp") {
	Ramp = RobotMap::shooterRamp;
}

void ShooterRamp::InitDefaultCommand() {
	SetDefaultCommand(new ShootRamp());
}


double ShooterRamp::getEncoder(){
	return Ramp->GetEncPosition();//up=+
}
void ShooterRamp::resetEncoder(){
	return Ramp->SetEncPosition(0);
}
void ShooterRamp::setRampSpeed(double speed){
	Ramp->Set(speed);
}
void ShooterRamp::brake(){
	Ramp->EnableCurrentLimit(true);
}
void ShooterRamp::unbrake(){
	Ramp->EnableCurrentLimit(true);
}
