// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef ROBOTMAP_H
#define ROBOTMAP_H

#define LOWBAR 0
#define PORTCULLIS 1
#define CHEVALDEFRISE 2
#define DEADBOT 3

#define PORTCULLIS1 4
#define PORTCULLIS2 5
#define PORTCULLIS3 6
#define CHEVALDEFRISE1 7
#define CHEVALDEFRISE2 8
#define CHEVALDEFRISE3 9

#define RAMPARTS 10
#define ROUGH_TERRAIN 11
#define K_P 1.0
#define K_I 0.0
#define K_D 0.250



#include "WPILib.h"
#include "CANTalon.h"


/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap {

public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static std::shared_ptr<CANTalon> chassisFrontLeft;
	static std::shared_ptr<CANTalon> chassisFrontRight;
	static std::shared_ptr<CANTalon> chassisBackLeft;
	static std::shared_ptr<CANTalon> chassisBackRight;
	static std::shared_ptr<RobotDrive> chassisRobotDrive;
	static std::shared_ptr<SpeedController> liftingMechHighLifty;
	static std::shared_ptr<SpeedController> liftingMechLowLifty;
	static std::shared_ptr<SpeedController> intakeLift;
	static std::shared_ptr<CANTalon> intakeWheels;

	static std::shared_ptr<Encoder> chassisFrontLeftEncoder;
	static std::shared_ptr<Encoder> chassisFrontRightEncoder;
	static std::shared_ptr<Encoder> chassisBackLeftEncoder;
	static std::shared_ptr<Encoder> chassisBackRightEncoder;
	static std::shared_ptr<Encoder> intakeLiftEncoder;

	//static std::shared_ptr<Encoder> shooterEncoder;
	static std::shared_ptr<CANTalon> shooterMotor;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	static void init();
};
#endif
