// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef OI_H
#define OI_H

#include "WPILib.h"

class OI {
private:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	std::shared_ptr<Joystick> xboxController;
	std::shared_ptr<JoystickButton> aButton;
	std::shared_ptr<JoystickButton> bButton;
	std::shared_ptr<JoystickButton> xButton;
	std::shared_ptr<JoystickButton> yButton;
	std::shared_ptr<JoystickButton> startButton;
	std::shared_ptr<JoystickButton> backButton;
	std::shared_ptr<JoystickButton> leftBumper;
	std::shared_ptr<JoystickButton> rightBumper;

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
	OI();

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES

	std::shared_ptr<Joystick> getXboxController();
	double getAxis(int a);
	double getRightXAxis();
	double getRightYAxis();
	double getLeftXAxis();
	double getLeftYAxis();
	double getTriggerAxis();
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
};

#endif
